name: Run Test Suite

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main            


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
       
      - uses: ./.github/actions/install-dependecies
       

      - name: Run pytest
        run: pytest 

  runmigrations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: ./.github/actions/install-dependecies

      - name: Run django migrate
        run: python manage.py migrate  
        
  checkmigrations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: ./.github/actions/install-dependecies

      - name: Run django migrations 
        run: python manage.py makemigrations --check           

    


